# Site settings
title: ely.io
email: e@ely.io
description: "Presenting my [aspiring] mad App-Building skills"
info: "More apps in the oven now so keep an eye out"
message: "Need an App Designed and Developed for you/yours, give me a Holla"
keywords: "mac,apple,iphone,ios,processing,design,hybrid,iPad,,apps,development"
baseurl: "/appstar/"
url: "http://www.ely.io" # the base hostname & protocol for your site
twitter_username: creativ_ely
# Build settings
markdown: kramdown
author:
    name: Ely Kahn
    twitter: creativ_ely
    url: http://www.ely.io
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: e@ely.io
facebook:
    image: /images/delightfuldev-facebook-cover.png
